include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true  # Uncomment to disable the `avoid_print` rule
    prefer_single_quotes: true  # Uncomment to enable the `prefer_single_quotes` rule
    constant_identifier_names: false
    non_constant_identifier_names: false
