name: dating
description: 'Sample dating app'
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_bloc: ^8.1.6
  cupertino_icons: ^1.0.8
  intl: ^0.19.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  json_serializable: ^6.8.0

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/images/
  fonts:
    - family: Ubuntu
      fonts:
        - asset: assets/fonts/Ubuntu-Bold.ttf
          weight: 500
        - asset: assets/fonts/Ubuntu-BoldItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Ubuntu-Italic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/Ubuntu-Medium.ttf
          weight: 400
        - asset: assets/fonts/Ubuntu-MediumItalic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Ubuntu-Regular.ttf
          weight: 300
